### ISSUE TITLE
NTP Time Zone

### ISSUE THREAD

**Issue by vangalvin** [jbaumann/H32_Basic#1]
In New Zealand our offsets are +12 NZST and +13NZDT.

I had to set the NTP Timezone offset to 12 and the NTP Daylight offset to 0 to get the correct time.

Or am I missing something?

**Comment by jbaumann** [comment]
NTP provides UTC, and the libraries normally do a pretty good job deciding when to use summer time. For those areas in the world where this doesn‘t work I have added the daylight offset for manual compensation.

TL;DR: You don‘t miss anything
