### ISSUE TITLE
Allow static IP to reduce radio-on time and battery consumption

### ISSUE THREAD

**Issue by dirkvdb2** [jbaumann/H32_Basic#3]
https://www.reddit.com/r/esp32/comments/e8n7p1/comment/faeje1c/

**Comment by jbaumann** [comment]
Hi @dirkvdb2 ,

thank you for contributing (even though your message is a bit short). I think it is a good choice for your first pull request, and I'm looking forward to reviewing your work.

Cheers, Joachim

**Comment by dirkvdb2** [comment]
Haha, fair enough but it would be my first pull request in 45 years of ‘programming’. Think: Sinclair QL, Pascal, Basic, 6508 and 68000 assembler, Mac Plus and the like. This is quite a different beast! But I might give it a try :-)

Dirk

Op za 23 sep. , Joachim Baumann ***@***.***(mailto:Op za 23 sep.  , Joachim Baumann <<a href=)> schreef:

**Comment by jbaumann** [comment]
It is implemented, on the Wifi config page as well as on the normal config page. A DNS entry has been added as well.
